name: Conda Workflow

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: s-weigand/setup-conda@v1.0.5
        with:
          activate-environment: myenv
          python-version: 3.9

      - name: Display PATH
        run: echo $PATH

      - name: Activate Conda Environment
        shell: bash
        run: |
          source ${{ github.workspace }}/miniconda/etc/profile.d/conda.sh
          conda activate myenv
          which python

      - name: Install dependencies
        shell: bash
        run: |
          source ${{ github.workspace }}/miniconda/etc/profile.d/conda.sh
          conda activate myenv
          conda install -c conda-forge some-package

      - name: Run tests
        shell: bash
        run: |
          source ${{ github.workspace }}/miniconda/etc/profile.d/conda.sh
          conda activate myenv
          pytest
