name: Conda Workflow

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: test
        run: find /Users/runner/work/_actions/

      - name: Set up Conda
        uses: s-weigand/setup-conda@main
        with:
        #  python-version: 3.9
        #  update-conda: true
        #  activate-conda: true

      - name: Display PATH
        run: echo $PATH

      - name: Manually activate Conda Environment
        shell: bash
        run: |
          source ${{ github.workspace }}/miniconda/etc/profile.d/conda.sh
          conda activate
          which python

      - name: Install dependencies
        shell: bash
        run: |
          source ${{ github.workspace }}/miniconda/etc/profile.d/conda.sh
          conda activate
          conda install -c conda-forge some-package

      - name: Run tests
        shell: bash
        run: |
          source ${{ github.workspace }}/miniconda/etc/profile.d/conda.sh
          conda activate
          pytest
